#
# Date:
# --------------------------------------------------------
#
#
DROP TABLE IF EXISTS tbl_Industry_Microvertical;
CREATE TABLE IF NOT EXISTS tbl_Industry_Microvertical (industry_name CHAR(39) NOT NULL default '', microvertical_name CHAR(100) NOT NULL default '', industryId INT(10) unsigned NOT NULL auto_increment, PRIMARY KEY (industryId) );
SET sql_mode='';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Aerospace & Defense';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Banking';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Building Materials, Clay & Glass';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Chemicals';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consolidated Companies';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Forest Products & Paper';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Furniture';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Heathcare';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Higher Education & Research';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Hospitality';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Insurance';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Metal Products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Nonclassifiable Establishments';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Oil & Gas';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Primary Metal & Steel';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Telecommunications';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Textiles Production';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Utilities';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Waste Management';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Aerospace & Defense',microvertical_name='Airlines & MRO  (Maintenance, Repair & Overhaul)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Aerospace & Defense',microvertical_name='Manufacturing & MRO  (Maintenance, Repair & Overhaul)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Financial Service Provider - Asset Finance & Leasing';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services -Automotive dealers';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services -Wholesale trade-durable goods';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services -Automotive repair, services, & parking';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services - Automotive dealers';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services - Automotive repair, services, & parking';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Sales & Services - Wholesale trade-durable goods';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Supplier - Fabricated metal products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Supplier - Industrial machinery & equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Supplier - Rubber & miscellaneous plastics products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Automotive',microvertical_name='Supplier - Transportation equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Banking',microvertical_name='Corporate';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Banking',microvertical_name='Financial service provider';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Banking',microvertical_name='Retail';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Building Materials, Clay & Glass',microvertical_name='Nonmetallic minerals, except fuels';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Building Materials, Clay & Glass',microvertical_name='Petroleum & coal products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Building Materials, Clay & Glass',microvertical_name='Stone, clay, glass, & concrete products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Chemicals',microvertical_name='Rubber & plastic products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Chemicals',microvertical_name='Standard';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consolidated Companies',microvertical_name='';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='AFS - Fashion (Apparel, Footwear/Jewelery, Watches, Clocks)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='AFS - Footwear (Apparel, Footwear/Jewelery, Watches, Clocks)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='AFS - Hometextiles (Apparel, Footwear/Jewelery, Watches, Clocks)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='AFS - JWC (Apparel, Footwear/Jewelery, Watches, Clocks)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='AFS - Others (Apparel, Footwear/Jewelery, Watches, Clocks)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Beverage - Breweries';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Beverage - Non-alcoholic';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Beverage - Wineries & distelleries';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Consumer durables';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Consumer electronics';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Bakery & cereals';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Canned, preserved & dried food';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Confectionary & snacks';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Cooking ingredients';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Dairy food';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Frozen food';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Food - Meat & fish products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Home appliances';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Personal care';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Pet food';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Consumer Products',microvertical_name='Tobacco';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='HCM - Payroll';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='HCM - Other';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='BI/BW - SEM';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='BI/BW - Other';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='CRM - SFA';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='CRM - Other';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='Financials';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Cross Industry ',microvertical_name='Portal';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider',microvertical_name='Brokerage';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider',microvertical_name='Corporate';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider',microvertical_name='Financial service provider';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider',microvertical_name='Investment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Financial Service Provider',microvertical_name='Retail';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Forest Products & Paper',microvertical_name='Forest products & paper - Lumber & wood products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Forest Products & Paper',microvertical_name='Forestry';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Forest Products & Paper',microvertical_name='Paper & allied products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Furniture',microvertical_name='Furniture & fixtures';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Furniture',microvertical_name='Lumber & wood products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Heathcare',microvertical_name='Healthcare services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Heathcare',microvertical_name='Social services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Computers, peripherals & storage';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Electronic components (non-semiconductor)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='EMS';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Instruments & test equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Imaging equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Medical laboratory equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Telecom network & broadcast equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Semiconductors & components';
INSERT INTO tbl_Industry_Microvertical SET industry_name='High Tech & Electronics',microvertical_name='Software';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Higher Education & Research',microvertical_name='Educational services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Higher Education & Research',microvertical_name='Engineering & management services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Hospitality',microvertical_name='Amusement';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Hospitality',microvertical_name='Hotels';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Hospitality',microvertical_name='Restaurants';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Hospitality',microvertical_name='Travel Services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Insurance',microvertical_name='Health';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Insurance',microvertical_name='Life';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Insurance',microvertical_name='Property & casualty';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Insurance',microvertical_name='Other';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience',microvertical_name='Biotechnology';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience',microvertical_name='Diagnostics';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience',microvertical_name='Medicinals & botanicals';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience',microvertical_name='Medical products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Lifescience',microvertical_name='Pharmaceuticals';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='ECO - Home building (Engineering, Construction &  Operations)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='ECO - Plant contracting & construction (Engineering, Construction &  Operations)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='ECO - Shipbuilding (incl. transportation equipment, NEC)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Air conditioning, heating equipment & industrial ovens';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Ball & roller bearings';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Electrical equipment, appliance & components';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Engine, turbine, compressor & pump machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Nedical, eeasuring & controlling devices';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Not assigned';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Components - Tools & metal working machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Air conditioning, heating equipment & industrial ovens';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Commercial & service industry machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Construction, mining, oil & gas machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Electrical equipment, appliance & components';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Elevators, conveyors, cranes & material h&ling equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Engine, turbine, compressor & pump machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Food machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Medical, measuring & controlling devices';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Packaging machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Special industry machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Textile machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Tools & metal working machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Machinery, Engineering & Construction',microvertical_name='IMC - Machinery - Woodworking, paper & printing machinery';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media',microvertical_name='Broadcasting';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media',microvertical_name='Entertainment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media',microvertical_name='Newspaper & magazines';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media',microvertical_name='Premium content publishing';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Media',microvertical_name='Others (e.g. media agencies, commercial printing etc.)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Metal Products',microvertical_name='Fabricated metal products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Metal Products',microvertical_name='Metal extraction';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Metal Products',microvertical_name='Metalforming & Treatment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Metal Products',microvertical_name='Sheet metal forming';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Agricultural Production - Livestock';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Agricultural Production - Crops';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Coal mining';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Fishing, hunting, & trapping';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Metal mining';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Mining',microvertical_name='Nonmetallic minerals, except fuels';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Nonclassifiable Establishments',microvertical_name='';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Oil & Gas',microvertical_name='Oil & Gas Downstream';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Oil & Gas',microvertical_name='Oil & Gas Upstream';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Oil & Gas',microvertical_name='Refining & manufacturing';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Oil & Gas',microvertical_name='Supply & trading';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Primary Metal & Steel',microvertical_name='Metalcasting';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Primary Metal & Steel',microvertical_name='Metalextraction';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Primary Metal & Steel',microvertical_name='Metalforming & treatment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Administration of economic programs';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Administration of human resources';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Environmental quality & housing';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Executive, legislative & general government';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Finance, taxation & monetary policy';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Justice, public order & safety';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Membership organizations';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Museums, art galleries, botanical & zoological gardens';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='National security & international affairs';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Public Sector',microvertical_name='Social services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Apparel stores';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Automotive dealers';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Building materials';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Food stores';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Furniture, home furnishings & equipment stores';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - General merch&ise';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Retail - Miscellaneous';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Apparel, piece goods & notions';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Chemicals & allied products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Electrical goods';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Beer, wine & distilled alcoholic beverages';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Farm-product raw materials';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Furniture & home furnishings';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Groceries & related products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Hardware, plumbing & heating equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Lumber & other construction materials';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Machinery, equipment & supplies';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Metals & minerals, except petroleum';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Miscellaneous durable goods';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Miscellaneous non-durable goods';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Motor verhicles & motor vehicle parts';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Paper & paper products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Professional & commercial equipment';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Retail',microvertical_name='Wholesale - Drugs, drug proprietaries & druggists\' sundries';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Service Industries - Employment agencies';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Service Industries - Facility management';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Service Industries - Real estate';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Agricultural services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Business services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Coal mining services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Forestry services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Metal mining services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Miscellaneous';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Other Services - Personal services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Postal services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Professional services - Audit & tax';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Professional Services - Consulting';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Professional Services - IT services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Professional Services - Legal services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Service Provider',microvertical_name='Transportation services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Telecommunications',microvertical_name='Telecommunications';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Textiles Production',microvertical_name='Textile mill products';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Logistic Service Providers - Railroad transport';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Logistic Service Providers - Transportation by air';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Logistic Service Providers - Trucking & warehouse';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Logistic Service Providers - Water transportation';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Other Service Industries - Real Estate';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Other Services - Transportation services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Post - Courier Express Parcel (CEP)';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Public Transportation - Local passenger transport';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Transportation & Shipping',microvertical_name='Public Transportation - Water transportation';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Utilities',microvertical_name='Electric, gas, & sanitary services';
INSERT INTO tbl_Industry_Microvertical SET industry_name='Waste Management',microvertical_name='Waste management & sanitary services';