#
# Date: 2008-08-21 23:03:44
# --------------------------------------------------------
#
#
DROP TABLE IF EXISTS tbl_countries;
CREATE TABLE IF NOT EXISTS tbl_countries (country_name CHAR(36) NOT NULL default '', regionId DECIMAL(1,0) NOT NULL, countryId INT(10) unsigned NOT NULL auto_increment, PRIMARY KEY (countryId) );
SET sql_mode='';
INSERT INTO tbl_countries SET country_name='Afghanistan',regionId=3;
INSERT INTO tbl_countries SET country_name='Albania',regionId=4;
INSERT INTO tbl_countries SET country_name='Algeria',regionId=4;
INSERT INTO tbl_countries SET country_name='American Samoa',regionId=3;
INSERT INTO tbl_countries SET country_name='Andorra',regionId=4;
INSERT INTO tbl_countries SET country_name='Angola',regionId=4;
INSERT INTO tbl_countries SET country_name='Anguilla',regionId=5;
INSERT INTO tbl_countries SET country_name='Antigua and Barbuda',regionId=5;
INSERT INTO tbl_countries SET country_name='Argentina',regionId=2;
INSERT INTO tbl_countries SET country_name='Armenia',regionId=4;
INSERT INTO tbl_countries SET country_name='Aruba',regionId=5;
INSERT INTO tbl_countries SET country_name='Ashmore and Cartier Islands',regionId=3;
INSERT INTO tbl_countries SET country_name='Australia',regionId=3;
INSERT INTO tbl_countries SET country_name='Austria',regionId=4;
INSERT INTO tbl_countries SET country_name='Azerbaijan',regionId=4;
INSERT INTO tbl_countries SET country_name='Bahamas',regionId=5;
INSERT INTO tbl_countries SET country_name='Bahrain',regionId=4;
INSERT INTO tbl_countries SET country_name='Bangladesh',regionId=3;
INSERT INTO tbl_countries SET country_name='Barbados',regionId=5;
INSERT INTO tbl_countries SET country_name='Belarus',regionId=4;
INSERT INTO tbl_countries SET country_name='Belgium',regionId=4;
INSERT INTO tbl_countries SET country_name='Belize',regionId=5;
INSERT INTO tbl_countries SET country_name='Benin',regionId=4;
INSERT INTO tbl_countries SET country_name='Bermuda',regionId=5;
INSERT INTO tbl_countries SET country_name='Bhutan',regionId=3;
INSERT INTO tbl_countries SET country_name='Bolivia',regionId=2;
INSERT INTO tbl_countries SET country_name='Bosnia and Herzegovina',regionId=4;
INSERT INTO tbl_countries SET country_name='Botswana',regionId=4;
INSERT INTO tbl_countries SET country_name='Bouvet Island',regionId=4;
INSERT INTO tbl_countries SET country_name='Brazil',regionId=2;
INSERT INTO tbl_countries SET country_name='British Virgin Islands',regionId=5;
INSERT INTO tbl_countries SET country_name='Brunei',regionId=3;
INSERT INTO tbl_countries SET country_name='Bulgaria',regionId=4;
INSERT INTO tbl_countries SET country_name='Burkina Faso',regionId=4;
INSERT INTO tbl_countries SET country_name='Burundi',regionId=4;
INSERT INTO tbl_countries SET country_name='Cambodia',regionId=3;
INSERT INTO tbl_countries SET country_name='Cameroon',regionId=4;
INSERT INTO tbl_countries SET country_name='Canada',regionId=2;
INSERT INTO tbl_countries SET country_name='Cape Verde',regionId=4;
INSERT INTO tbl_countries SET country_name='Cayman Islands',regionId=5;
INSERT INTO tbl_countries SET country_name='Central African Republic',regionId=4;
INSERT INTO tbl_countries SET country_name='Chad',regionId=4;
INSERT INTO tbl_countries SET country_name='Chile',regionId=2;
INSERT INTO tbl_countries SET country_name='China',regionId=3;
INSERT INTO tbl_countries SET country_name='Christmas Island',regionId=3;
INSERT INTO tbl_countries SET country_name='Cocos (Keeling) Islands',regionId=3;
INSERT INTO tbl_countries SET country_name='Colombia',regionId=2;
INSERT INTO tbl_countries SET country_name='Comoros',regionId=4;
INSERT INTO tbl_countries SET country_name='Congo',regionId=4;
INSERT INTO tbl_countries SET country_name='Costa Rica',regionId=5;
INSERT INTO tbl_countries SET country_name='Cote d\'Ivoire',regionId=4;
INSERT INTO tbl_countries SET country_name='Croatia',regionId=4;
INSERT INTO tbl_countries SET country_name='Cuba',regionId=5;
INSERT INTO tbl_countries SET country_name='Cyprus',regionId=4;
INSERT INTO tbl_countries SET country_name='Czech Republic',regionId=4;
INSERT INTO tbl_countries SET country_name='Denmark',regionId=4;
INSERT INTO tbl_countries SET country_name='Djibouti',regionId=4;
INSERT INTO tbl_countries SET country_name='Dominica',regionId=5;
INSERT INTO tbl_countries SET country_name='Dominican Republic',regionId=5;
INSERT INTO tbl_countries SET country_name='Ecuador',regionId=2;
INSERT INTO tbl_countries SET country_name='Egypt',regionId=4;
INSERT INTO tbl_countries SET country_name='El Salvador',regionId=5;
INSERT INTO tbl_countries SET country_name='Equatorial Guinea',regionId=4;
INSERT INTO tbl_countries SET country_name='Eritrea',regionId=4;
INSERT INTO tbl_countries SET country_name='Estonia',regionId=4;
INSERT INTO tbl_countries SET country_name='Ethiopia',regionId=4;
INSERT INTO tbl_countries SET country_name='Falkland Islands (Malvinas)',regionId=5;
INSERT INTO tbl_countries SET country_name='Faroe Islands',regionId=4;
INSERT INTO tbl_countries SET country_name='Fiji',regionId=3;
INSERT INTO tbl_countries SET country_name='Finland',regionId=4;
INSERT INTO tbl_countries SET country_name='France',regionId=4;
INSERT INTO tbl_countries SET country_name='Gabon',regionId=4;
INSERT INTO tbl_countries SET country_name='Gambia',regionId=4;
INSERT INTO tbl_countries SET country_name='Georgia',regionId=4;
INSERT INTO tbl_countries SET country_name='Germany',regionId=4;
INSERT INTO tbl_countries SET country_name='Ghana',regionId=4;
INSERT INTO tbl_countries SET country_name='Gibraltar',regionId=4;
INSERT INTO tbl_countries SET country_name='Greece',regionId=4;
INSERT INTO tbl_countries SET country_name='Greenland',regionId=4;
INSERT INTO tbl_countries SET country_name='Grenada',regionId=5;
INSERT INTO tbl_countries SET country_name='Guadeloupe',regionId=5;
INSERT INTO tbl_countries SET country_name='Guam',regionId=5;
INSERT INTO tbl_countries SET country_name='Guatemala',regionId=2;
INSERT INTO tbl_countries SET country_name='Guinea',regionId=3;
INSERT INTO tbl_countries SET country_name='Guinea-Bissau',regionId=3;
INSERT INTO tbl_countries SET country_name='Guyana',regionId=5;
INSERT INTO tbl_countries SET country_name='Haiti',regionId=5;
INSERT INTO tbl_countries SET country_name='Honduras',regionId=5;
INSERT INTO tbl_countries SET country_name='Hong Kong',regionId=3;
INSERT INTO tbl_countries SET country_name='Hungary',regionId=4;
INSERT INTO tbl_countries SET country_name='Iceland',regionId=4;
INSERT INTO tbl_countries SET country_name='India',regionId=3;
INSERT INTO tbl_countries SET country_name='Indonesia',regionId=3;
INSERT INTO tbl_countries SET country_name='Iran',regionId=4;
INSERT INTO tbl_countries SET country_name='Iraq',regionId=4;
INSERT INTO tbl_countries SET country_name='Ireland',regionId=4;
INSERT INTO tbl_countries SET country_name='Israel',regionId=4;
INSERT INTO tbl_countries SET country_name='Italy',regionId=4;
INSERT INTO tbl_countries SET country_name='Jamaica',regionId=5;
INSERT INTO tbl_countries SET country_name='J3n',regionId=3;
INSERT INTO tbl_countries SET country_name='Jordan',regionId=4;
INSERT INTO tbl_countries SET country_name='Kazakhstan',regionId=4;
INSERT INTO tbl_countries SET country_name='Kenya',regionId=4;
INSERT INTO tbl_countries SET country_name='Korea, North',regionId=3;
INSERT INTO tbl_countries SET country_name='Korea, South',regionId=3;
INSERT INTO tbl_countries SET country_name='Kuwait',regionId=4;
INSERT INTO tbl_countries SET country_name='Laos',regionId=3;
INSERT INTO tbl_countries SET country_name='Latvia',regionId=4;
INSERT INTO tbl_countries SET country_name='Lebanon',regionId=4;
INSERT INTO tbl_countries SET country_name='Lesotho',regionId=4;
INSERT INTO tbl_countries SET country_name='Liberia',regionId=4;
INSERT INTO tbl_countries SET country_name='Libya',regionId=4;
INSERT INTO tbl_countries SET country_name='Liechtenstein',regionId=4;
INSERT INTO tbl_countries SET country_name='Lithuania',regionId=4;
INSERT INTO tbl_countries SET country_name='Luxembourg',regionId=4;
INSERT INTO tbl_countries SET country_name='Macau',regionId=3;
INSERT INTO tbl_countries SET country_name='Macedonia',regionId=4;
INSERT INTO tbl_countries SET country_name='Madagascar',regionId=4;
INSERT INTO tbl_countries SET country_name='Malawi',regionId=4;
INSERT INTO tbl_countries SET country_name='Malaysia',regionId=3;
INSERT INTO tbl_countries SET country_name='Maldives',regionId=3;
INSERT INTO tbl_countries SET country_name='Mali',regionId=4;
INSERT INTO tbl_countries SET country_name='Malta',regionId=4;
INSERT INTO tbl_countries SET country_name='Marshall Islands',regionId=3;
INSERT INTO tbl_countries SET country_name='Martinique',regionId=5;
INSERT INTO tbl_countries SET country_name='Mauritania',regionId=4;
INSERT INTO tbl_countries SET country_name='Mauritius',regionId=4;
INSERT INTO tbl_countries SET country_name='Mayotte',regionId=4;
INSERT INTO tbl_countries SET country_name='Mexico',regionId=2;
INSERT INTO tbl_countries SET country_name='Micronesia, Federated States of',regionId=3;
INSERT INTO tbl_countries SET country_name='Moldova',regionId=4;
INSERT INTO tbl_countries SET country_name='Monaco',regionId=4;
INSERT INTO tbl_countries SET country_name='Mongolia',regionId=3;
INSERT INTO tbl_countries SET country_name='Montserrat',regionId=5;
INSERT INTO tbl_countries SET country_name='Morocco',regionId=4;
INSERT INTO tbl_countries SET country_name='Mozambique',regionId=4;
INSERT INTO tbl_countries SET country_name='Myanmar',regionId=3;
INSERT INTO tbl_countries SET country_name='Namibia',regionId=4;
INSERT INTO tbl_countries SET country_name='Nauru',regionId=3;
INSERT INTO tbl_countries SET country_name='Nepal',regionId=3;
INSERT INTO tbl_countries SET country_name='Netherlands',regionId=4;
INSERT INTO tbl_countries SET country_name='Netherlands Antilles',regionId=4;
INSERT INTO tbl_countries SET country_name='New Caledonia',regionId=3;
INSERT INTO tbl_countries SET country_name='New Zealand',regionId=3;
INSERT INTO tbl_countries SET country_name='Nicaragua',regionId=5;
INSERT INTO tbl_countries SET country_name='Niger',regionId=4;
INSERT INTO tbl_countries SET country_name='Nigeria',regionId=4;
INSERT INTO tbl_countries SET country_name='Niue',regionId=3;
INSERT INTO tbl_countries SET country_name='Norfolk Island',regionId=3;
INSERT INTO tbl_countries SET country_name='Northern Mariana Islands',regionId=3;
INSERT INTO tbl_countries SET country_name='Norway',regionId=4;
INSERT INTO tbl_countries SET country_name='Oman',regionId=4;
INSERT INTO tbl_countries SET country_name='Pakistan',regionId=3;
INSERT INTO tbl_countries SET country_name='Palau',regionId=3;
INSERT INTO tbl_countries SET country_name='Panama',regionId=5;
INSERT INTO tbl_countries SET country_name='Papua New Guinea',regionId=3;
INSERT INTO tbl_countries SET country_name='Paraguay',regionId=2;
INSERT INTO tbl_countries SET country_name='Peru',regionId=2;
INSERT INTO tbl_countries SET country_name='Philippines',regionId=3;
INSERT INTO tbl_countries SET country_name='Poland',regionId=4;
INSERT INTO tbl_countries SET country_name='Portugal',regionId=4;
INSERT INTO tbl_countries SET country_name='Puerto Rico',regionId=2;
INSERT INTO tbl_countries SET country_name='Qatar',regionId=4;
INSERT INTO tbl_countries SET country_name='Reunion',regionId=4;
INSERT INTO tbl_countries SET country_name='Romania',regionId=4;
INSERT INTO tbl_countries SET country_name='Russia',regionId=4;
INSERT INTO tbl_countries SET country_name='Rwanda',regionId=4;
INSERT INTO tbl_countries SET country_name='Saint Helena',regionId=4;
INSERT INTO tbl_countries SET country_name='Saint Kitts and Nevis',regionId=5;
INSERT INTO tbl_countries SET country_name='Saint Lucia',regionId=5;
INSERT INTO tbl_countries SET country_name='Saint Pierre and Miquelon',regionId=5;
INSERT INTO tbl_countries SET country_name='Saint Vincent and the Grenadines',regionId=5;
INSERT INTO tbl_countries SET country_name='San Marino',regionId=4;
INSERT INTO tbl_countries SET country_name='Sao Tome and Principe',regionId=4;
INSERT INTO tbl_countries SET country_name='Saudi Arabia',regionId=4;
INSERT INTO tbl_countries SET country_name='Senegal',regionId=4;
INSERT INTO tbl_countries SET country_name='Seychelles',regionId=4;
INSERT INTO tbl_countries SET country_name='Sierra Leone',regionId=4;
INSERT INTO tbl_countries SET country_name='Singapore',regionId=3;
INSERT INTO tbl_countries SET country_name='Slovakia',regionId=4;
INSERT INTO tbl_countries SET country_name='Slovenia',regionId=4;
INSERT INTO tbl_countries SET country_name='Solomon Islands',regionId=3;
INSERT INTO tbl_countries SET country_name='Somalia',regionId=4;
INSERT INTO tbl_countries SET country_name='South Africa',regionId=4;
INSERT INTO tbl_countries SET country_name='Spain',regionId=4;
INSERT INTO tbl_countries SET country_name='Sri Lanka',regionId=3;
INSERT INTO tbl_countries SET country_name='Sudan',regionId=4;
INSERT INTO tbl_countries SET country_name='Suriname',regionId=5;
INSERT INTO tbl_countries SET country_name='Svalbard',regionId=4;
INSERT INTO tbl_countries SET country_name='Swaziland',regionId=4;
INSERT INTO tbl_countries SET country_name='Sweden',regionId=4;
INSERT INTO tbl_countries SET country_name='Switzerland',regionId=4;
INSERT INTO tbl_countries SET country_name='Syria',regionId=4;
INSERT INTO tbl_countries SET country_name='Taiwan',regionId=3;
INSERT INTO tbl_countries SET country_name='Tajikistan',regionId=4;
INSERT INTO tbl_countries SET country_name='Tanzania',regionId=4;
INSERT INTO tbl_countries SET country_name='Thailand',regionId=3;
INSERT INTO tbl_countries SET country_name='Togo',regionId=4;
INSERT INTO tbl_countries SET country_name='Tonga',regionId=3;
INSERT INTO tbl_countries SET country_name='Trinidad and Tobago',regionId=5;
INSERT INTO tbl_countries SET country_name='Tunisia',regionId=4;
INSERT INTO tbl_countries SET country_name='Turkey',regionId=4;
INSERT INTO tbl_countries SET country_name='Turkmenistan',regionId=4;
INSERT INTO tbl_countries SET country_name='Turks and Caicos Islands',regionId=5;
INSERT INTO tbl_countries SET country_name='Tuvalu',regionId=3;
INSERT INTO tbl_countries SET country_name='Uganda',regionId=4;
INSERT INTO tbl_countries SET country_name='Ukraine',regionId=4;
INSERT INTO tbl_countries SET country_name='United Arab Emirates',regionId=4;
INSERT INTO tbl_countries SET country_name='United Kingdom',regionId=4;
INSERT INTO tbl_countries SET country_name='United States',regionId=2;
INSERT INTO tbl_countries SET country_name='United States Minor Outlying Islands',regionId=5;
INSERT INTO tbl_countries SET country_name='Uruguay',regionId=2;
INSERT INTO tbl_countries SET country_name='Uzbekistan',regionId=4;
INSERT INTO tbl_countries SET country_name='Vanuatu',regionId=3;
INSERT INTO tbl_countries SET country_name='Vatican City State',regionId=4;
INSERT INTO tbl_countries SET country_name='Venezuela',regionId=2;
INSERT INTO tbl_countries SET country_name='Vietnam',regionId=3;
INSERT INTO tbl_countries SET country_name='Virgin Islands, U.S.',regionId=5;
INSERT INTO tbl_countries SET country_name='Wallis and Futuna',regionId=3;
INSERT INTO tbl_countries SET country_name='Western Sahara',regionId=4;
INSERT INTO tbl_countries SET country_name='Yemen',regionId=4;
INSERT INTO tbl_countries SET country_name='Yugoslavia',regionId=4;
INSERT INTO tbl_countries SET country_name='Zaire',regionId=4;
INSERT INTO tbl_countries SET country_name='Zambia',regionId=4;
INSERT INTO tbl_countries SET country_name='Zimbabwe',regionId=4;